name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: |
          yarn
      - name: Build
        run: |
          yarn build
      - name: npm setup
        run: |
          echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" >> ~/.npmrc
          echo "@$(echo "$REPOSITORY_OWNER" |  tr '[:upper:]' '[:lower:]' ):registry=https://npm.pkg.github.com" >> ~/.npmrc
        env:
          REPOSITORY_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ github.token }}
      - name: npm publish
        run: |
          npm publish
